default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: msg_dev

test:
  <<: *default
  database: msg_test

production:
  <<: *default
  database: msg_prod